---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    azure_k8s_teardown: false
    azure_k8s_ssh_dir: "../sshkeys"
    azure_instances:
      host01:
        type: client
        ip: 192.168.61.11
      host02:
        type: server
        ip: 192.168.61.12
  roles:
    - azure-instances
