---
- hosts: remote
  become: yes
  vars:
    iperf_server: true
  roles:
    - tools
    - iperf
- hosts: clients
  become: yes
  vars:
    crictl_container_engine: crio
  roles:
    - cri-o
    - crictl
- hosts: remote
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      loop:
        - co-clim.yaml
        - co-nolim.yaml
        - co-mlim.yaml
        - po-clim.yaml
        - po-nolim.yaml
        - po-mlim.yaml
